### ISSUE TITLE
sh ./prune.sh games SASRec 0.3 50 log 0 运行时出错

### ISSUE THREAD

**Issue by wuren519** [Linxyhaha/DEALRec#4]
Traceback (most recent call last):
  File "prune.py", line 15, in <module>
    effort = get_effort_score(args)
  File "/workspace/code/DEALRec/code/prune/effort_score.py", line 154, in get_effort_score
    trainer = Effort_Trainer(
  File "/root/anaconda3/envs/DEALRec/lib/python3.8/site-packages/transformers/trainer.py", line 504, in __init__
    self._move_model_to_device(model, args.device)
  File "/root/anaconda3/envs/DEALRec/lib/python3.8/site-packages/transformers/trainer.py", line 728, in _move_model_to_device
    model = model.to(device)
AttributeError: '_IncompatibleKeys' object has no attribute 'to'

**Comment by Linxyhaha** [comment]
It seems that the model is not successfully loaded. Please ensure the model is successfully loaded or initialized.
