### ISSUE TITLE
在使用了作者提供的模型后，任然报错element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by xkai-boy** [Linxyhaha/DEALRec#7]
Traceback (most recent call last):
  File "/share_data/DEALRec-main/code/prune/prune.py", line 15, in <module>
    effort = get_effort_score(args)
  File "/share_data/DEALRec-main/code/prune/effort_score.py", line 199, in get_effort_score
    gradients = trainer.get_grad(resume_from_checkpoint=resume_from_checkpoint)
  File "/share_data/DEALRec-main/code/prune/effort_util.py", line 361, in get_grad
    return inner_training_loop(
  File "/share_data/DEALRec-main/code/prune/effort_util.py", line 654, in _inner_training_loop
    gradient = self.training_step(model, inputs)
  File "/share_data/DEALRec-main/code/prune/effort_util.py", line 706, in training_step
    self.accelerator.backward(torch.mean(loss), retain_graph=True)
  File "/root/anaconda3/envs/DEALRec/lib/python3.9/site-packages/accelerate/accelerator.py", line 1921, in backward
    self.scaler.scale(loss).backward(**kwargs)
  File "/root/anaconda3/envs/DEALRec/lib/python3.9/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/root/anaconda3/envs/DEALRec/lib/python3.9/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
请问作者大大这是什么原因导致的呢，，似乎好像是前面并没有进行计算存储，导致现在这里没有张量可以再做计算

**Comment by xkai-boy** [comment]
![1](https://github.com/user-attachments/assets/a57f7f21-bbf5-43c6-8010-b902b78bf7fd)
![2](https://github.com/user-attachments/assets/9ea01eb4-2d3f-4547-bb3e-fdcdd107b247)
还有一个问题，我认为可能也是导致这个报错的原因，请作者打打看图片中的画黄色波浪线的包，是在您提供的包里面没有的，我通过自己的方法去下载了部分包，但是导致我的整个环境混乱了，或者有的包直接无法下载，请作者大大查看您提供的包是否完整，谢谢

**Comment by xkai-boy** [comment]
已解决

**Comment by zozni-douzone** [comment]
How did you solve it? The same problem occurs.

**Comment by xkai-boy** [comment]
Your version of PEFT may not be used correctly. You can go to GitHub to find the source code of PEFT, and then find 0.3.0.dev0 in the tag（ https://github.com/huggingface/peft/releases/tag/v0.3.0 ）Finally, the installation should be completed.
















At 2025-01-09 17:03:27, "zozni-douzone" ***@***.***> wrote:

How did you solve it? The same problem occurs.

**Comment by AigoLee** [comment]
您好，请问下现在没有dev0 tag了，请问有什么解决方法吗

**Comment by AigoLee** [comment]
我安装了 https://github.com/huggingface/peft/releases/tag/v0.3.0 的源码，但是还是有这个错误“RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn”

**Comment by Linxyhaha** [comment]
> 我安装了 https://github.com/huggingface/peft/releases/tag/v0.3.0 的源码，但是还是有这个错误“RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn”

你可以试一试以下指令安装peft，相见[issue](https://github.com/tloen/alpaca-lora/issues/293)
```
pip uninstall peft -y
pip install git+https://github.com/huggingface/peft.git@e536616888d51b453ed354a6f1e243fecb02ea08
```
